package org.castafiore.erp.utils;

public class CSSUtil {
	
	public final static String[] HOVERS = new String[]{"grow",
		"shrink",
		"pulse",
		"pulse-grow",
		"pulse-shrink",
		"push",
		"pop",
		"rotate",
		"grow-rotate",
		"float",
		"sink",
		"hover",
		"hang",
		"skew",
		"skew-forward" ,
		"skew-backward" ,
		"wobble-vertical" ,
		"wobble-to-bottom-right",
		"wobble-to-top-right",
		"wobble-top",
		"wobble-bottom",
		"wobble-skew",
		"buzz",
		"buzz-out",
		"border-fade",
		"hollow",
		"trim",
		"outline-outward" ,
		"outline-inward" ,
		"round-corners" ,

		"glow",
		"box-shadow-outset"  ,
		"box-shadow-inset"  ,
		"float-shadow" ,
		"hover-shadow" ,
		"shadow-radial" ,

		"bubble-top" ,
		"bubble-right" ,
		"bubble-bottom" ,
		"bubble-left" ,
		"bubble-float-top" ,
		"bubble-float-right"  ,
		"bubble-float-bottom"  ,
		"bubble-float-left"  ,

		"curl-top-left",
		"curl-top-right",
		"curl-bottom-right",
		"curl-bottom-left"};

}
